name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: |
          npm install
          npm ci
          npm test

  build-docker-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.USERNAME }}/reporting-service .

  push-docket-image:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.USERNAME }}/reporting-service

      # Vous pouvez ajouter ici des étapes supplémentaires, comme le déploiement de l'image
